package com.nyayamitra.service;

import com.nyayamitra.model.Document;
import com.nyayamitra.model.DocumentTemplate;
import com.nyayamitra.model.User;
import com.nyayamitra.repository.DocumentRepository;
import com.nyayamitra.repository.DocumentTemplateRepository;
import com.nyayamitra.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.io.ByteArrayOutputStream;
import java.util.*;

@Service
public class DocumentService {
    
    @Autowired
    private DocumentRepository documentRepository;
    
    @Autowired
    private DocumentTemplateRepository templateRepository;
    
    @Autowired
    private UserRepository userRepository;
    
    public List<DocumentTemplate> getAllTemplates() {
        return templateRepository.findByIsActiveTrue();
    }
    
    public DocumentTemplate getTemplateById(String id) {
        return templateRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Template not found"));
    }
    
    public List<DocumentTemplate> getTemplatesByType(Document.DocumentType type) {
        return templateRepository.findByIsActiveTrueAndType(type);
    }
    
    public Document generateDocument(Map<String, Object> request, String email) {
        User user = userRepository.findByEmail(email)
            .orElseThrow(() -> new RuntimeException("User not found"));
        
        DocumentTemplate template = templateRepository.findById(
                (String) request.get("templateId"))
            .orElseThrow(() -> new RuntimeException("Template not found"));
        
        Document document = new Document();
        document.setUserId(user.getId());
        document.setUserName(user.getFirstName() + " " + user.getLastName());
        document.setTitle((String) request.get("title"));
        document.setType(template.getType());
        document.setCategory(template.getCategory());
        document.setSubType(template.getSubType());
        document.setFormData((Map<String, Object>) request.get("formData"));
        document.setStatus(Document.DocumentStatus.DRAFT);
        document.setCourtFee(template.getEstimatedCourtFee());
        document.setStampDuty(template.getEstimatedStampDuty());
        document.setState((String) request.getOrDefault("state", user.getState()));
        document.setTemplateId(template.getId());
        document.setVersion(1);
        document.setCreatedAt(new Date());
        document.setUpdatedAt(new Date());
        
        // Generate content from template
        String content = populateTemplate(template.getTemplateContent(), 
            (Map<String, Object>) request.get("formData"));
        document.setContent(content);
        
        return documentRepository.save(document);
    }
    
    public List<Document> getDocumentsForUser(String email) {
        User user = userRepository.findByEmail(email)
            .orElseThrow(() -> new RuntimeException("User not found"));
        return documentRepository.findByUserId(user.getId());
    }
    
    public Document getDocumentById(String id, String email) {
        User user = userRepository.findByEmail(email)
            .orElseThrow(() -> new RuntimeException("User not found"));
        
        Document document = documentRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Document not found"));
        
        if (!document.getUserId().equals(user.getId())) {
            throw new RuntimeException("Unauthorized access");
        }
        
        return document;
    }
    
    public byte[] generatePDF(String documentId, String email) {
        Document document = getDocumentById(documentId, email);

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        com.itextpdf.kernel.pdf.PdfWriter writer = new com.itextpdf.kernel.pdf.PdfWriter(baos);
        com.itextpdf.kernel.pdf.PdfDocument pdf = new com.itextpdf.kernel.pdf.PdfDocument(writer);
        com.itextpdf.layout.Document doc = new com.itextpdf.layout.Document(pdf);

        // Add title
        com.itextpdf.layout.element.Paragraph title = new com.itextpdf.layout.element.Paragraph(document.getTitle())
            .setFontSize(16)
            .setBold()
            .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER);
        doc.add(title);

        doc.add(new com.itextpdf.layout.element.Paragraph("\n"));

        // Add content
        String[] lines = document.getContent().split("\n");
        for (String line : lines) {
            doc.add(new com.itextpdf.layout.element.Paragraph(line).setFontSize(11));
        }

        // Add footer
        doc.add(new com.itextpdf.layout.element.Paragraph("\n\n---\nGenerated by NyayaMitra - Legal Document Management System")
            .setFontSize(8)
            .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER)
            .setItalic());

        doc.close();

        // Update document status
        document.setStatus(Document.DocumentStatus.GENERATED);
        document.setDownloadedAt(new Date());
        documentRepository.save(document);

        return baos.toByteArray();
    }
    
    public void deleteDocument(String id, String email) {
        Document document = getDocumentById(id, email);
        documentRepository.delete(document);
    }
    
    private String populateTemplate(String template, Map<String, Object> data) {
        String result = template;
        if (data != null) {
            for (Map.Entry<String, Object> entry : data.entrySet()) {
                String placeholder = "{{" + entry.getKey() + "}}";
                String value = entry.getValue() != null ? entry.getValue().toString() : "";
                result = result.replace(placeholder, value);
            }
        }
        return result;
    }
}
